---
# https://docs.gitea.com/installation/install-from-binary/

- name: Create Gitea system group
  ansible.builtin.group:
    name: "{{ gitea_group }}"
    system: true

- name: Create user to run Gitea
  ansible.builtin.user:
    name: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    home: "{{ gitea_home }}"
    shell: /bin/bash
    system: true
    create_home: true

- name: Create required directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0750"
  loop:
    - "{{ gitea_data_dir }}"
    - "{{ gitea_data_dir }}/custom"
    - "{{ gitea_data_dir }}/log"
    - "{{ gitea_data_dir }}/data"

- name: Create gitea config directory
  ansible.builtin.file:
    path: "{{ gitea_config_dir }}"
    state: directory
    owner: root
    group: "{{ gitea_group }}"
    mode: "0770"

- name: Download Gitea binary file
  ansible.builtin.get_url:
    url: "https://dl.gitea.com/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
    dest: "{{ gitea_binary_path }}"
    checksum: "sha256:https://dl.gitea.com/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64.sha256"
    owner: root
    group: root
    mode: "0755"
  notify: restart gitea

- name: Deploy Gitea configuration
  ansible.builtin.template:
    src: app.ini.j2
    dest: "{{ gitea_config_dir }}/app.ini"
    owner: root
    group: "{{ gitea_group }}"
    mode: "0640"
  notify: restart gitea

- name: Deploy Gitea systemd unit
  ansible.builtin.template:
    src: gitea.service.j2
    dest: /etc/systemd/system/gitea.service
    mode: "0644"
  notify:
    - reload systemd
    - restart gitea

- name: Enable and start Gitea
  ansible.builtin.systemd:
    name: gitea
    enabled: true
    state: started
    daemon_reload: true
