# ======================================================================================== #
# ROLE: Common Configuration
# Applied to all hosts across all OS versions.
# ======================================================================================== #
---
# LOAD VARS --------------------------------------------------- #
# Load OS-based variables using 'OS Family' name to read relevant file.
# Deprecated Version: `include_vars: "{{ ansible_os_family }}.yml"`
- name: "Load OS Variables"
  include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: "Common: Service Accounts"
  ansible.builtin.import_tasks: common-accounts.yml

- name: "Common: Package Management"
  ansible.builtin.import_tasks: common-packages.yml
