# INVENTORY FILE ------------------------------------- #
# Default Groups:
#  all - Contains every host. 
#  ungrouped - Contains all hosts that do not belong to any other group.

# Parent/child relationships among groups.
# - In INI format, use the :children suffix.
# - In YAML format, use the children: entry.

# [proxmox_nodes:children]
# proxmox_prd
# proxmox_dev

[proxmox_nodes]
10.0.10.1
10.0.10.2
10.0.10.3

[git]
10.0.20.10
