name: "Infrastructure: Proxmox Cluster"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Deployment Action: Plan, Apply, Destroy"
        required: true
        default: plan
        type: choice
        options:
          - plan
          - apply
          - destroy
  push:
    branches:
      - main
    paths:
      - ".gitea/workflows/infra-proxmox.yaml"
      - "variables/global-proxmox.tfvars"
      - "terraform/platform/proxmox-cluster/**"
  pull_request:
    branches:
      - main
    paths:
      - ".gitea/workflows/infra-proxmox.yaml"
      - "variables/global-proxmox.tfvars"
      - "terraform/platform/proxmox-cluster/**"

jobs:
  # PLAN ------------------------------------------------------- #
  plan:
    uses: ./.gitea/workflows/sub-terraform-plan.yaml
    with: # Inputs passed to template job.
      stack_name: infra-proxmox
      working_directory: ./terraform/platform/proxmox-cluster
      run_mode: ${{ inputs.action }}
      terraform_version: "1.16.1"
    secrets: # Secrets must be declared separately from inputs and passed explicitly.
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      PVE_AUTH_API_TOKEN: ${{ secrets.PVE_AUTH_API_TOKEN }}

  # APPLY / DESTROY -------------------------------------------- #
  apply:
    needs: plan # REQUIRES the plan job to succeed before running.
    if: gitea.event.inputs.action == 'apply' || gitea.event.inputs.action == 'destroy'
    uses: ./.gitea/workflows/sub-terraform-apply.yaml
    with: # Inputs passed to template job.
      stack_name: infra-proxmox
      working_directory: ./terraform/platform/proxmox-cluster
      run_mode: ${{ inputs.action }}
      terraform_version: "1.16.1"
    secrets: # Secrets must be declared separately from inputs and passed explicitly.
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      PVE_AUTH_API_TOKEN: ${{ secrets.PVE_AUTH_API_TOKEN }}
