name: "Terraform: Apply" # Display name shown in the GitHub Actions UI.

on: # Define workflow triggers.
  workflow_call: # Allows this workflow to be called by a parent workflow.
    inputs: # Define input parameters accepted from the calling workflow.
      working_directory: # Path to the Terraform root module (passed in from parent workflow).
        type: string
        required: true
      stack_name: # String used with plan and variable file naming.
        type: string
        required: true
      run_mode: # Pass in 'run_mode' to use as parameter in plan command (plan -destroy).
        type: string
        required: true
      terraform_version: # String value for required Terraform version to install.
        type: string
        required: true
    secrets: # Secrets must be declared separately from inputs.
      ARM_TENANT_ID:
        required: true # Azure tenant ID for backend resources.
      ARM_CLIENT_ID:
        required: true # Azure Service Principal ID for authentication.
      ARM_CLIENT_SECRET:
        required: true # Azure Service Principal Client Secret authentication.
      PVE_API_TERRAFORM_TOKEN:
        required: true # Proxmox API token, used for Proxmox authentication.

jobs:
  apply:
    name: "Terraform: Apply" # Display name for this job in the UI.
    runs-on: ubuntu-latest # Use the latest GitHub-hosted Ubuntu runner.
    timeout-minutes: 45 # Fail the entire job if it exceeds this duration.
    environment: ${{ inputs.stack_name }} # Use stack name matching GitHub environment.
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }} # All 'run' steps execute from this directory by default.

    env:
      # General ----------------------------------- #
      STACK_NAME: ${{ inputs.stack_name }} # Current stack name used for plan file and artifact naming.
      RUN_MODE: ${{ inputs.run_mode == 'destroy' && '-destroy' || '' }} # If run_mode is 'destroy', set RUN_MODE to '-destroy' for Terraform plan command.

      # Azure Authentication  ----------------------------------- #
      # Used to access and store Terraform remote backend state files.
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }} # Azure tenant ID, get from repo variable.
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }} # Azure Service Principal ID, sourced from repo secret.
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }} # Azure Service Principal secret, sourced from repo secret.
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }} # Subscription containing the Terraform backend Storage Account.

      # Terraform Backend Config ----------------------------------- #
      TF_BACKEND_RG: ${{ vars.TF_BACKEND_RESOURCE_GROUP }} # Azure Resource Group containing the backend Storage Account.
      TF_BACKEND_SA: ${{ vars.TF_BACKEND_STORAGE_ACCOUNT }} # Azure Storage Account used for Terraform remote states.
      TF_BACKEND_CONTAINER: ${{ vars.TF_BACKEND_STORAGE_CONTAINER }} # Blob container within the Storage Account holding state files.
      TF_BACKEND_KEY: "${{ inputs.stack_name }}.tfstate" # Filename of the state file within the container for the stack.

      # Terraform Variable Files ----------------------------------- #
      TF_VARS_DIR: "../../../variables" # Relative path from working_directory to the variables folder.
      TF_VARS_FILE: "${{ inputs.stack_name }}.tfvars" # Stack-specific filename, passed in from the parent workflow.

    steps:
      - uses: actions/checkout@v7 # Clone the repository onto the runner.

      - uses: hashicorp/setup-terraform@v4 # Install Terraform CLI on the runner.
        with:
          terraform_version: ${{ inputs.TF_VERSION }} # Pin to the version defined in the parent workflow.

      - name: "Terraform: Initialize"
        timeout-minutes: 5 # Fail this step if it exceeds 'x' minutes.
        run: |
          terraform init \
           -backend-config="resource_group_name=$TF_BACKEND_RG" \
           -backend-config="storage_account_name=$TF_BACKEND_SA" \
           -backend-config="container_name=$TF_BACKEND_CONTAINER" \
           -backend-config="key=$TF_BACKEND_KEY" \
           -backend-config="use_azuread_auth=true"

      - name: "Download Plan Artifact"
        uses: actions/download-artifact@v7
        with:
          name: "${{ inputs.stack_name }}_${{ inputs.run_mode }}.plan" # Artifact name.
          path: "${{ inputs.working_directory }}" # Path to the saved plan file produced in the plan step.

      - name: "Terraform: Apply"
        env:
          PLAN_FILE: "${{ inputs.stack_name }}_${{ inputs.run_mode }}.plan"
        run: terraform apply --auto-approve "$PLAN_FILE"
