name: Gitea Actions - TEST
run-name: ${{ gitea.actor }} is testing out Gitea Actions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: development
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  Test-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ gitea.event_name }} event"
      - run: echo "This job is running on a ${{ runner.os }} server"
      - run: echo "Repository = ${{ gitea.repository }} | Branch = ${{ gitea.ref }}"
      - run: echo "The job status is ${{ job.status }}"
      - run: echo "Target Environment = '{{ inputs:environment }}'"

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: |
          ls ${{ gitea.workspace }}
