# ========================================================================================================= #
# Proxmox: Cluster Options
# Description:
# - Manages Proxmox VE Cluster Datacenter options.
# https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/cluster_options
# ========================================================================================================= #

# Proxmox: Cluster Configuration ------------------------------------------- #

resource "proxmox_cluster_options" "options" {
  description               = "Proxmox Cluster" # Shown in the web-interface datacenter notes panel.
  language                  = "en"
  keyboard                  = "en-us"
  mac_prefix                = "BC:24:11" # Prefix for autogenerated MAC addresses. "BC:24:11" is default for Proxmox.
  next_id = {
    lower = 200 # The ranges for the next free VM ID auto-selection pool.
    upper = 999
  }
}

# Proxmox: Resource Pools ------------------------------------------- #

resource "proxmox_virtual_environment_pool" "main" {
    for_each = var.pve_pools
    pool_id  = each.key
    comment  = each.value
}
