# ======================================================================================== #
# PLAYBOOK: Proxmox - Template (Ubuntu Server)
# Deploy/upgrade VM template in Proxmox.
# Usage: ansible-playbook -i inventory/main.ini playbooks/pve-template-ubuntu.yml
# ======================================================================================== #

---
- name: "Proxmox: Deploy Template (Ubuntu Server)"
  #hosts: "{{ groups['proxmox_nodes'][0] }}"
  hosts: proxmox_nodes # Run on all Proxmox nodes. "{{ groups['proxmox_nodes'][0] }}" # Run on first node in group only.
  become: true
  gather_facts: true
  roles:
    - proxmox-template-ubuntu
