---
# Proxmox Authentication ----------------------------------------- #
proxmox_user: "root"
#proxmox_pass: "" # Pass in via terminal variable.

# Proxmox Groups ----------------------------------------- #

# Service Accounts ----------------------------------------- #
ssh_key_path: "../../../../../files/ssh_keys"

service_accounts_pve:
  - name: "svc-ansible@pam"
    description: "Service Account: Ansible"
  - name: svc-terraform@pve
    description: "Service Account: Terraform"
  - name: svc-packer@pve
    description: "Service Account: Packer"

service_accounts_local:
  - name: "svc-ansible"
    groups: "sudo"
    state: "present"
