---
# ================================================== #
# Configure Gitea Runner
# ================================================== #

# Install Docker to use runners in containers locally.
- name: Install Docker
  ansible.builtin.package:
    name: docker.io
    state: present

- name: Create Gitea-Runner System Group
  ansible.builtin.group:
    name: "{{ runner_group }}"
    system: true

# Run as a systemd service.
# Create an unprivileged user, install the binary, and register the runner as that user so the .runner file ends up in the service’s working directory.
- name: Create Gitea-Runner User
  ansible.builtin.user:
    name: "{{ runner_user }}"
    group: "{{ runner_group }}"
    home: "{{ runner_home }}"
    shell: /bin/bash
    system: true
    create_home: true

- name: Add Gitea-Runner User to Docker Group
  ansible.builtin.user:
    name: "{{ runner_user }}"
    groups: docker
    append: yes

- name: Download Gitea-Runner Binary
  ansible.builtin.get_url:
    url: "https://dl.gitea.com/gitea-runner/{{ runner_version }}/gitea-runner-{{ runner_version }}-linux-amd64"
    dest: "/opt/gitea-runner-{{ runner_version }}-linux-amd64"
    checksum: "sha256:https://dl.gitea.com/gitea-runner/{{ runner_version }}/gitea-runner-{{ runner_version }}-linux-amd64.sha256"
    owner: root
    group: root
    mode: "0755"

- name: Install Gitea-Runner
  ansible.builtin.shell: install -m 0755 "/opt/gitea-runner-{{ runner_version }}-linux-amd64" /usr/local/bin/gitea-runner

# Create Gitea-Runner Config Directory
- name: Create Gitea-Runner Config Directory
  ansible.builtin.file:
    path: /etc/gitea-runner
    state: directory
    mode: "0775"
    owner: root
    group: "{{ runner_group }}"

# Generate Gitea runner configuration as the gitea-runner user account.
# The 'shell' module is required instead of 'command' because of the '>'.
# Using 'command' module doesn't invoke a shell, so redirection operators are passed through as literal argument text rather than interpreted.
- name: Generate Gitea-Runner Configuration
  become: true
  become_user: "{{ runner_user }}"
  ansible.builtin.shell: gitea-runner config generate > /etc/gitea-runner/config.yaml

# Obtain Runner Token Value
# https://docs.gitea.com/usage/actions/runner/
# TEST: sudo -u gitea gitea --config /etc/gitea/app.ini actions generate-runner-token
- name: Obtain Runner Token Value
  become: true
  become_user: "{{ gitea_user }}"
  ansible.builtin.shell: gitea --config /etc/gitea/app.ini actions generate-runner-token
  register: runner_token

# Register Runner Using Token
# https://docs.gitea.com/runner/registration/
- name: Register Gitea-Runner Configuration
  become: true
  become_user: "{{ runner_user }}"
  ansible.builtin.shell: |
    cd /var/lib/gitea-runner
    gitea-runner register -c /etc/gitea-runner/config.yaml --no-interactive --instance {{ runner_instance }} --name {{ runner_name }} --token {{ runner_token.stdout }}
  when:
    - runner_token.stdout is defined

- name: Deploy Gitea-Runner systemd Unit
  ansible.builtin.template:
    src: gitea-runner.service.j2
    dest: /etc/systemd/system/gitea-runner.service
    mode: "0644"
  notify:
    - reload systemd
    - restart gitea-runner
