---
gitea_version: "1.27.2"
gitea_user: git
gitea_group: git
gitea_home: /home/git
gitea_data_dir: /var/lib/gitea
gitea_config_dir: /etc/gitea
gitea_binary_path: /usr/local/bin/gitea
gitea_domain: "git.tshand.net"
gitea_http_port: 443
gitea_ssh_port: 2222 # Gitea SSH server for git operations, kept on separate port from default.
